[#ftl]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote of the day</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/images/favicon.png" rel="icon" type="image/png">
</head>
<body style="background-image: url(${image});">
<blockquote>${quote}</blockquote>
</body>
</html>
